<?php
/**
 * Implements hook_block_info()
 */

function apprenticeships_map_block_info() {
	$blocks['apprenticeships_map_home'] = array(
		'info' => t('Apprenticeships Home Page Map'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);
	$blocks['apprenticeships_map_internal'] = array(
		'info' => t('Apprenticeships Internal Map'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);
	return $blocks;
}

/**
 * Implements hook_block_view()
 */

function apprenticeships_map_block_view($delta = '') {
	switch ($delta) {
		case 'apprenticeships_map_home':
			$location = 'home';
			$block['subject'] = t('Find an Australian Apprenticeship Centre');
			$block['title'] = t('Find an AAC');
			$block['content']['wrapper'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'class' => array($location . '-map'),
				),
			);
			$block['content']['wrapper']['body'] = array(
				'#prefix' => '<p>',
				'#markup' => t('<a href="@url" title="Find an Australian Apprenticeship Centre near you">Find an Australian Apprenticeships Centre</a>', array('@url' => url('find-my-aac/full-list'))),
				'#suffix' => '</p>',
			);
			$block['content']['wrapper']['map-canvas'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'id' => array("map-canvas-" . $location),
				),
			);
			$block['content']['wrapper']['map-feedback'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'id' => 'map-feedback',
				),
			);
			$block['content']['wrapper']['map-overlay'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'id' => 'map-overlay',
				),
			);
			$block['content']['wrapper']['form-wrapper'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'class' => $location . '-map-form-wrapper',
				),
			);
			$block['content']['wrapper']['form-wrapper']['form-body'] = drupal_get_form('apprenticeships_map_aac_search');
			$block['content']['wrapper']['footer'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'class' => 'region-search',
				),
			);
			$block['content']['wrapper']['footer']['content'] = array(
				'#prefix' => '<p>',
				'#markup' => t('<a href="@url" title="Find my AAC by region">Find an AAC by region</a>', array('@url' => url('find-my-aac/by-region'))),
				'#suffix' => '</p>',
			);
		break;

		case 'apprenticeships_map_internal':
			$location = 'internal';
			$block['subject'] = t('Find an Australian Apprenticeship Centre');
			$block['subject'] = t('Find an Australian Apprenticeship Centre');
			$block['content']['wrapper'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'class' => array($location . '-map'),
				),
			);
			$block['content']['wrapper']['body'] = array(
				'#prefix' => '<p>',
				'#markup' => t('<a href="@url" title="Find an Australian Apprenticeship Centre near you">Find an Australian Apprenticeships Centre</a>', array('@url' => url('find-my-aac/full-list'))),
				'#suffix' => '</p>',
			);
			$block['content']['wrapper']['map-canvas'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'id' => array("map-canvas-" . $location),
				),
			);
			$block['content']['wrapper']['map-feedback'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'id' => 'map-feedback',
				),
			);
			$block['content']['wrapper']['map-overlay'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'id' => 'map-overlay',
				),
			);
			$block['content']['wrapper']['form-wrapper'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'class' => $location . '-map-form-wrapper',
				),
			);
			$block['content']['wrapper']['form-wrapper']['text'] = array(
				'#prefix' => '<p>',
				'#markup' => 'Enter your search terms below. You can do a simple text search for the city, postcode or company name.',
				'#suffix' => '</p>',
			);
			$block['content']['wrapper']['form-wrapper']['form-body'] = drupal_get_form('apprenticeships_map_aac_search', $location);
			$block['content']['wrapper']['footer'] = array(
				'#type' => 'container',
				'#attributes' => array(
					'class' => 'region-search',
				),
			);
			$block['content']['wrapper']['footer']['content'] = array(
				'#prefix' => '<p>',
				'#markup' => t('<a href="@url" title="Find my AAC by region">Find an AAC by region.</a>', array('@url' => url('find-my-aac/by-region'))),
				'#suffix' => '</p>',
			);
		break;
	}
	return $block;
}

function apprenticeships_map_aac_search($form_state, $location) {

	$base_path = drupal_get_path('module', 'apprenticeships_map');

	$apprenticeships_map_settings = array(
		'basePath' => $base_path,
	);

	drupal_add_js(array('apprenticeships_map' => $apprenticeships_map_settings), 'setting');
	drupal_add_js('https://maps.googleapis.com/maps/api/js?client=gme-readingroom&sensor=true', array(
		'type' => 'external',
		'weight' => 0,
	));
	drupal_add_js($base_path . '/js/infobox_packed.js', array(
		'weight' => 5,
	));
	drupal_add_js($base_path . '/js/jquery.placeholder.min.js', array(
		'weight' => 5,
	));
	drupal_add_js($base_path . '/js/apprenticeships_map.js', array(
		'scope' => 'footer',
	));

	$form['location'] = array(
		'#title' => t('Location'),
		'#type' => 'textfield',
		'#size' => 10,
		'#attributes' => array(
			'placeholder' => t('City, Suburb'),
		),
	);

	$form['keywords'] = array(
		'#title' => t('Keywords'),
		'#type' => 'textfield',
		'#size' => 10,
		'#attributes' => array(
			'placeholder' => t('Keywords'),
		),
	);

	$form['submit'] = array(
		'#type' => 'button',
		'#value' => 'Search',
	);

	$form['#submit'] = array('apprenticeships_map_aac_search_submit');
	$form['#attributes']['class'] = array('search-block-form');

	return $form;
}

function apprenticeships_map_aac_search_submit($form, &$form_state) {
	drupal_set_message(t('Form submitted!'));
	// Load some behaviour here.
}

function apprenticeships_map_aac_search_validate($form, &$form_state) {
	
	$location = $form_state['values']['location'];
	$keywords = $form_state['values']['keywords'];

	if (!$location && !$keywords) {
		form_set_error('location', 'Please enter a location or one or more keywords.');
		form_set_error('keywords', '');
	}
}

/**
 * Implements hook_init()
 */

function apprenticeships_map_init(){
	//drupal_add_js('js/apprenticeships_map.js', 'file');
	if(request_path()=='map_do_search'){
		set_time_limit(3600);
		$search_result = apprenticeships_map_do_search();
		echo json_encode($search_result['find']);
		exit;
	}
}

/**
 *  This function is the core function of the module.
 */

function apprenticeships_map_do_search(){
	error_reporting(E_ALL);
	ini_set('display_errors', TRUE);
	ini_set('display_startup_errors', TRUE);


	$results = array();

	//Using google api parse coordinate
	$keywords = ( $_REQUEST["term"] );
	$location = urlencode( $_REQUEST["location"] );
	$region = ( $_REQUEST["region"] );

	if(empty($location) && empty($keywords)){
		$query = db_select('node', 'n');
		$query->fields('n', array('nid'))->distinct();
		$query->condition('n.status', 1);
		$query->addTag('node_access');
		$query->condition('n.type', 'australian_apprenticeship_centre');
		$query->orderBy('n.title');
		$db_result = $query->execute()->fetchAll();
		return _apprenticeships_map_populate_nodes($db_result);
	}

	if(!empty($location)){
		$url = "http://maps.googleapis.com/maps/api/geocode/json?address=".$location.",+AU&sensor=false";
		$geocode_object = json_decode( file_get_contents($url) );

		if(count($geocode_object->results)>0 && isset($geocode_object->results[0]->geometry->location) ){
			$lat = $geocode_object->results[0]->geometry->location->lat;
			$lng = $geocode_object->results[0]->geometry->location->lng;		
		}	
	}
	
	if(empty($keywords)){
		$sql  = "SELECT
			node.*,
			entity_id,
			bundle,
			deleted,
			field_data_field_aac_location.field_aac_location_lat ,
			field_data_field_aac_location.field_aac_location_lon ,
			ACOS( SIN( RADIANS( field_aac_location_lat ) ) * SIN( RADIANS( :lat ) ) + COS( RADIANS( field_aac_location_lat ) ) * COS( RADIANS( :lat )) * COS( RADIANS( field_aac_location_lon ) - RADIANS( :lng )) ) * 6380 AS distance

			FROM field_data_field_aac_location 

			LEFT JOIN node ON field_data_field_aac_location.entity_id = node.nid
			WHERE
			deleted = 0
			AND node.status = 1
			ORDER BY distance";

		$db_result = db_query($sql, array(
			":lat" => $lat,
			":lng"=>$lng,
		)) -> fetchAll();

		return _apprenticeships_map_populate_nodes($db_result);
	}

	// query our search index, joined to our nodes table
	$query = db_select('search_index', 'i', array(
		'target' => 'slave',
		))->extend('SearchQuery');
	$query->join('node', 'n', 'n.nid = i.sid');
	// search term
	$query->searchExpression(preg_replace("/[^a-zA-Z0-9 ]/s", "", $keywords), 'node');
	
	$query->fields('n', array('nid'))->distinct();
	$query->condition('n.status', 1);
	$query->addTag('node_access');
	$query->condition('n.type', 'australian_apprenticeship_centre');

	if(!empty($location)){
		$query->join('field_data_field_aac_location', 'coords', 'n.nid = coords.entity_id');
		$query->condition('coords.entity_type', 'node');	
		$query->orderBy("ACOS( SIN( RADIANS( field_aac_location_lat ) ) * SIN( RADIANS( $lat ) ) + COS( RADIANS( field_aac_location_lat ) ) * COS( RADIANS( $lat )) * COS( RADIANS( field_aac_location_lon ) - RADIANS( $lng )) ) * 6380 ","ASC");
	}

	_node_rankings($query);

	$db_result = $query->execute()->fetchAll();

	return _apprenticeships_map_populate_nodes($db_result);
}

function _apprenticeships_map_administrative_area($abbrv){
	$administrative_area = array(
		"ACT" => "Australian Capital Territory",
		"NSW" => "New South Wales",
		"NT"  => "Northern Territory",
		"QLD" => "Queensland",
		"SA"  => "South Australia",
		"TAS" => "Tasmania",
		"VIC" => "Victoria",
		"WA"  => "Western Australia",	
	);
	$abbrv = strtoupper($abbrv);
	return $administrative_area[$abbrv];
}

function _apprenticeships_map_populate_nodes($db_result){
	$records= array();
	foreach ($db_result as $record) {
		$node_alias = drupal_get_path_alias('node/'.$record->nid);
		$node = node_load( $record->nid );
		$node->node_alias = $node_alias;
		$type_tid = $node->field_aac_type['und'][0]['tid'];
		if(!empty($type_tid)){
			$node->type = taxonomy_term_load($type_tid)->name;
		}
		if(!empty($node->field_aac_address['und'][0]['administrative_area'])){
			$node->field_aac_address['und'][0]['administrative_area'] = _apprenticeships_map_administrative_area($node->field_aac_address['und'][0]['administrative_area']);	
			$node->field_aac_address['und'][0]['country'] = "Australia";
		}
		
		$records[] = $node;
	}

	$results["find"] = $records;	
	return $results ;
}
